# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
 
    - name: Build and Publish Web App
      run: msbuild ScoreApp.sln /p:Configuration=Release
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ScoreApp_Executable
        path: bin\Release
        
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1
        release_name: v1
        draft: true
        prerelease: false
        
    - name: Archive release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: bin\Release
        filename: ScoreApp.zip

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ScoreApp.zip
        asset_name: ScoreApp.zip
        asset_content_type: application/zip

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
